#!/usr/bin/env python
"""Phase 4 — package the student for one-command local serving with Ollama.

Three jobs:
1. **Merge + save** the trained student to a standalone HF checkpoint
   (`paths.merged_dir`). For a full fine-tune this just re-serializes the
   model in fp16; for a LoRA/QLoRA run it merges the adapter into the base
   first (Unsloth's `save_pretrained_merged` if available, else PEFT's
   `merge_and_unload`).
2. **Print the GGUF conversion commands** (llama.cpp `convert_hf_to_gguf.py`
   + `llama-quantize`) — GGUF is what Ollama/llama.cpp load.
3. **Write an Ollama `Modelfile`** with the correct ChatML template + the
   distilled `SYSTEM` prompt, and print the `ollama create` / `ollama run`
   one-liners.

Steps 2–3 need no GPU and no heavy deps, so `--modelfile-only` runs on the
laptop to inspect/emit the Modelfile without touching the weights.

Usage (GPU box):
    python scripts/export_ollama.py                       # merge + Modelfile + instructions
    python scripts/export_ollama.py --quant Q5_K_M
    python scripts/export_ollama.py --modelfile-only      # laptop: just emit Modelfile
    python scripts/export_ollama.py --llama-cpp ~/src/llama.cpp
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[1]
if str(_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(_ROOT / "src"))

from distil_task.config import ensure_dir, load_config, resolve_path
from distil_task.prompts import STUDENT_SYSTEM_PROMPT

# ChatML template (Qwen2.5 / most Unsloth instruct bases). Ollama fills
# .System / .Prompt / .Response; the stop tokens keep the student from
# rambling past one JSON object.
#
# CRITICAL: the user turn must reproduce the EXACT scaffold the student was
# trained on (distil_task.prompts.build_extraction_user_prompt wraps the
# document in <document>...</document> + "Output:"). Feeding the raw pasted
# invoice without that scaffold is a silent quality-killer for a 0.5B student
# trained on one rigid format.
CHATML_TEMPLATE = """\
{{ if .System }}<|im_start|>system
{{ .System }}<|im_end|>
{{ end }}{{ if .Prompt }}<|im_start|>user
<document>
{{ .Prompt }}
</document>
Output:<|im_end|>
{{ end }}<|im_start|>assistant
{{ .Response }}<|im_end|>
"""


def build_modelfile(gguf_filename: str | None,
                    system_prompt: str = STUDENT_SYSTEM_PROMPT) -> str:
    """Render a complete Ollama Modelfile string.

    When ``gguf_filename`` is None (or the file doesn't exist yet) the
    Modelfile uses ``FROM .`` — Ollama's safetensors-dir import, which needs
    no llama.cpp checkout. Note: Ollama's built-in converter has produced a
    GGUF that crashes llama.cpp's sampler for this fine-tuned Qwen2.5 base
    (Assertion `found` at llama-sampling.cpp:660); if that happens, build the
    GGUF with llama.cpp's convert_hf_to_gguf.py instead (commands printed by
    this script) and point FROM at it.
    """
    from_line = f"FROM ./{gguf_filename}" if gguf_filename else "FROM ."
    # Ollama Modelfile multi-line values use triple-quoted blocks.
    return (
        f"# Ollama Modelfile for the distilled invoice-extraction student.\n"
        f"# Generated by scripts/export_ollama.py. Register + run:\n"
        f"#     ollama create distil-invoice -f Modelfile\n"
        f"#     ollama run distil-invoice \"<paste invoice text>\"\n"
        f"# (FROM . imports the safetensors in this dir; pass a GGUF filename\n"
        f"#  to build_modelfile / rebuild via llama.cpp for a quantized file.)\n\n"
        f"{from_line}\n\n"
        f'TEMPLATE """{CHATML_TEMPLATE}"""\n\n'
        f'SYSTEM """{system_prompt}"""\n\n'
        f"# Deterministic extraction: no sampling, stop on the ChatML turn markers.\n"
        f"PARAMETER temperature 0\n"
        f"PARAMETER top_p 1\n"
        f"PARAMETER num_ctx 4096\n"
        f'PARAMETER stop "<|im_end|>"\n'
        f'PARAMETER stop "<|im_start|>"\n'
    )


def gguf_instructions(
    merged_dir: Path,
    gguf_f16: Path,
    gguf_quant: Path,
    quant: str,
    llama_cpp: str,
) -> str:
    """The exact llama.cpp commands to turn the merged HF model into a
    quantized GGUF that Ollama can load."""
    lc = llama_cpp.rstrip("/\\")
    return (
        "# 1. Convert the merged HF checkpoint to a full-precision GGUF:\n"
        f"python {lc}/convert_hf_to_gguf.py \"{merged_dir}\" \\\n"
        f"    --outfile \"{gguf_f16}\" --outtype f16\n\n"
        f"# 2. Quantize it to {quant} (smaller + faster; good quality for a 3B):\n"
        f"{lc}/llama-quantize \"{gguf_f16}\" \"{gguf_quant}\" {quant}\n"
    )


def merge_student(
    student_dir: Path,
    out_dir: Path,
    base_model: str,
    max_seq_length: int,
) -> str:
    """Merge/serialize the student into `out_dir`. Returns the method used.

    Order: Unsloth (fastest, handles both full + LoRA) -> transformers/PEFT.
    Heavy imports are lazy so this file stays importable on a CPU-only box.
    """
    ensure_dir(out_dir)
    has_adapter = (student_dir / "adapter_config.json").exists()

    # --- Unsloth path -------------------------------------------------------
    try:
        from unsloth import FastLanguageModel  # noqa: PLC0415

        model, tok = FastLanguageModel.from_pretrained(
            str(student_dir),
            max_seq_length=max_seq_length,
            load_in_4bit=False,
        )
        # merged_16bit works for both a full FT and a merged LoRA.
        model.save_pretrained_merged(str(out_dir), tok, save_method="merged_16bit")
        return "unsloth:merged_16bit"
    except ImportError:
        pass

    # --- transformers / PEFT fallback --------------------------------------
    import torch  # noqa: PLC0415
    from transformers import AutoModelForCausalLM, AutoTokenizer  # noqa: PLC0415

    dtype = torch.float16
    if has_adapter:
        from peft import PeftModel  # noqa: PLC0415

        base = AutoModelForCausalLM.from_pretrained(base_model, torch_dtype=dtype)
        model = PeftModel.from_pretrained(base, str(student_dir))
        model = model.merge_and_unload()
        tok = AutoTokenizer.from_pretrained(str(student_dir))
        method = "peft:merge_and_unload"
    else:
        model = AutoModelForCausalLM.from_pretrained(str(student_dir), torch_dtype=dtype)
        tok = AutoTokenizer.from_pretrained(str(student_dir))
        method = "transformers:resave_fp16"

    model.save_pretrained(str(out_dir), safe_serialization=True)
    tok.save_pretrained(str(out_dir))
    return method


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--config", default=None)
    ap.add_argument("--model", default=None, help="student checkpoint dir (default paths.student_dir)")
    ap.add_argument("--out", default=None, help="merged output dir (default paths.merged_dir)")
    ap.add_argument("--name", default="distil-invoice", help="Ollama model name")
    ap.add_argument("--quant", default="Q4_K_M", help="llama-quantize type (Q4_K_M, Q5_K_M, Q8_0, ...)")
    ap.add_argument("--llama-cpp", default="/path/to/llama.cpp",
                    help="path to your llama.cpp checkout (for the printed commands)")
    ap.add_argument("--modelfile-only", action="store_true",
                    help="skip merging weights; just write the Modelfile + print instructions (laptop-safe)")
    args = ap.parse_args()

    cfg = load_config(args.config)
    student_dir = Path(args.model) if args.model else resolve_path(cfg, "student_dir")
    merged_dir = Path(args.out) if args.out else resolve_path(cfg, "merged_dir")
    base_model = str(cfg["training"]["base_model"])
    max_seq = int(cfg["training"]["max_seq_length"])

    ensure_dir(merged_dir)

    # ---- 1. merge -------------------------------------------------------------
    if args.modelfile_only:
        print("[merge] skipped (--modelfile-only)")
        method = "skipped"
    else:
        if not student_dir.exists():
            print(f"[error] student dir not found: {student_dir}\n"
                  f"        train first (scripts/train.py) or pass --modelfile-only.")
            return 1
        print(f"[merge] {student_dir} -> {merged_dir}")
        method = merge_student(student_dir, merged_dir, base_model, max_seq)
        print(f"[merge] done via {method}")

    # ---- 2. GGUF conversion instructions -------------------------------------
    gguf_f16 = merged_dir / f"{args.name}-f16.gguf"
    gguf_quant = merged_dir / f"{args.name}-{args.quant.lower()}.gguf"
    instructions = gguf_instructions(merged_dir, gguf_f16, gguf_quant, args.quant, args.llama_cpp)

    # ---- 3. Modelfile ---------------------------------------------------------
    # Prefer the quantized GGUF when it actually exists; otherwise emit the
    # dependency-free safetensors import (FROM .).
    modelfile_text = build_modelfile(
        gguf_quant.name if gguf_quant.exists() else None)
    modelfile_path = merged_dir / "Modelfile"
    modelfile_path.write_text(modelfile_text, encoding="utf-8")

    run_cmds = (
        f"# Register the model with Ollama (run from {merged_dir}):\n"
        f"cd \"{merged_dir}\"\n"
        f"ollama create {args.name} -f Modelfile\n\n"
        f"# One-liner to run it locally:\n"
        f"ollama run {args.name} \"$(cat path/to/invoice.txt)\"\n"
    )

    print("\n" + "=" * 70)
    print("GGUF conversion (llama.cpp) — run these on the GPU/build box:")
    print("=" * 70)
    print(instructions)
    print("=" * 70)
    print(f"Wrote Ollama Modelfile -> {modelfile_path}")
    print("=" * 70)
    print(run_cmds)
    print(f"[done] merge={method}  modelfile={modelfile_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
